//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Date
    {
        public int ApplicantID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Applicant_Application Applicant_Application { get; set; }
    }
}
