//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Application
    {
        public int ApplicantID { get; set; }
        public int ALCurID { get; set; }
        public int OLCurID { get; set; }
        public int StreamID { get; set; }
        public int ZScoreID { get; set; }
        public int MeanID { get; set; }
        public int Subject1ID { get; set; }
        public int Subject1GradeID { get; set; }
        public int Subject2ID { get; set; }
        public int Subject2GradeID { get; set; }
        public int Subject3ID { get; set; }
        public int Subject3GradeID { get; set; }
        public int EnglishGradeID { get; set; }
        public int OLMathsGradeID { get; set; }
        public int OLEnglishGradeID { get; set; }
        public int OLScienceGradeID { get; set; }
        public int FoundationResultID { get; set; }
        public int DistrictID { get; set; }
        public int DegreeID { get; set; }
        public int SelectionStatusID { get; set; }
    
        public virtual AL_Curriculum AL_Curriculum { get; set; }
        public virtual AL_Stream AL_Stream { get; set; }
        public virtual DegreeProgram DegreeProgram { get; set; }
        public virtual District District { get; set; }
        public virtual Foundation_Result Foundation_Result { get; set; }
        public virtual MeanResult MeanResult { get; set; }
        public virtual OL_Curriculum OL_Curriculum { get; set; }
        public virtual Selection_Status Selection_Status { get; set; }
        public virtual Subject1 Subject1 { get; set; }
        public virtual Subject2 Subject2 { get; set; }
        public virtual Subject3 Subject3 { get; set; }
        public virtual SubjectGrade SubjectGrade { get; set; }
        public virtual SubjectGrade SubjectGrade1 { get; set; }
        public virtual SubjectGrade SubjectGrade2 { get; set; }
        public virtual SubjectGrade SubjectGrade3 { get; set; }
        public virtual SubjectGrade SubjectGrade4 { get; set; }
        public virtual SubjectGrade SubjectGrade5 { get; set; }
        public virtual SubjectGrade SubjectGrade6 { get; set; }
        public virtual User User { get; set; }
        public virtual ZScore ZScore { get; set; }
        public virtual Applicant_Date Applicant_Date { get; set; }
    }
}
