//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Extra
    {
        public int ApplicantID { get; set; }
        public int ExtraID { get; set; }
        public string Description { get; set; }
    
        public virtual SportsnExtra_Level SportsnExtra_Level { get; set; }
        public virtual User User { get; set; }
    }
}
