//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUSH_DBEntities : DbContext
    {
        public AUSH_DBEntities()
            : base("name=AUSH_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AL_Curriculum> AL_Curriculum { get; set; }
        public virtual DbSet<AL_Stream> AL_Stream { get; set; }
        public virtual DbSet<Applicant_Application> Applicant_Application { get; set; }
        public virtual DbSet<Applicant_Date> Applicant_Date { get; set; }
        public virtual DbSet<Applicant_Extra> Applicant_Extra { get; set; }
        public virtual DbSet<Applicant_Sports> Applicant_Sports { get; set; }
        public virtual DbSet<DegreeProgram> DegreePrograms { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Foundation_Result> Foundation_Result { get; set; }
        public virtual DbSet<IQQuestion> IQQuestions { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<MeanResult> MeanResults { get; set; }
        public virtual DbSet<OL_Curriculum> OL_Curriculum { get; set; }
        public virtual DbSet<Selection_Status> Selection_Status { get; set; }
        public virtual DbSet<SportsnExtra_Level> SportsnExtra_Level { get; set; }
        public virtual DbSet<Subject1> Subject1 { get; set; }
        public virtual DbSet<Subject2> Subject2 { get; set; }
        public virtual DbSet<Subject3> Subject3 { get; set; }
        public virtual DbSet<SubjectGrade> SubjectGrades { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ZScore> ZScores { get; set; }
    }
}
