//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject2()
        {
            this.Applicant_Application = new HashSet<Applicant_Application>();
        }
    
        public int Subject2ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int StreamID { get; set; }
    
        public virtual AL_Stream AL_Stream { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Application> Applicant_Application { get; set; }
    }
}
